name: Custom runner workflow
on: push

jobs:
  build: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Test Runner
        run: |
          echo "Running on: $HOSTNAME"
          echo "Working Directory: $PWD"
  
  osinfo:
    runs-on: self-hosted
    steps:
      - uses:  actions/checkout@v2
      - name: find os info
        run: |
          lscpu
          sleep 30
          cat /etc/fstab
          sleep 30
          echo "$(df -h /)"